#!/bin/sh

HTPASSWD=/etc/perceus/htpasswd


if which htpasswd >/dev/null 2>&1; then
 APP=$(which htpasswd)
elif which htpasswd2 >/dev/null 2>&1; then
 APP=$(which htpasswd2)
else
   echo "ERROR: the command 'htpasswd' or 'htpasswd2' was not found! Check path or install it."
   exit 1
fi

statedir=`perceus info config statedir`

if [ -z "$1" ]; then
   echo "USAGE: $0 (options) [username]"
   echo
   echo "OPTIONS:"
   echo
   echo "  -D    Delete the specified user"
   echo "  -m    MD5 encrypt the passwd entry"
   echo "  -p    No encryption of the password"
   echo
   exit 1
fi

if grep -q "^httpd:" /etc/passwd; then
   WWWGRP=httpd
elif grep -q "^apache:" /etc/passwd; then
   WWWGRP=apache
elif grep -q "^wwwrun:" /etc/passwd; then
   WWWGRP=www
else
   echo "ERROR: What is the web server default username?"
   exit 1
fi

for arg in $@; do
   LINE="$LINE $LAST"
   LAST=$arg
done

LINE="$LINE $HTPASSWD $LAST"   

touch $HTPASSWD
$APP $LINE
chmod 640 $HTPASSWD
chgrp $WWWGRP $HTPASSWD
chgrp $WWWGRP $statedir/database/*
chmod g+rw $statedir/database/*

